const books = [
	{
		id: 1,
		title: "Laskar Pelangi",
		author: "Andrea Hirata",
		year: 2005,
		description: "Kisah perjuangan sekelompok anak di Belitung dalam mengejar pendidikan dan meraih impian.",
		image: "https://picsum.photos/seed/laskar-pelangi/300/450",
	},
	{
		id: 2,
		title: "Bumi Manusia",
		author: "Pramoedya Ananta Toer",
		year: 1980,
		description: "Novel yang menceritakan kehidupan Minke dan perjuangannya menghadapi ketidakadilan pada masa kolonial.",
		image: "https://picsum.photos/seed/bumi-manusia/300/450",
	},
	{
		id: 3,
		title: "Negeri 5 Menara",
		author: "Ahmad Fuadi",
		year: 2009,
		description: "Kisah persahabatan dan perjuangan para santri dalam mengejar cita-cita melalui pendidikan.",
		image: "https://picsum.photos/seed/negeri-5-menara/300/450",
	},
	{
		id: 4,
		title: "Ronggeng Dukuh Paruk",
		author: "Ahmad Tohari",
		year: 1982,
		description: "Cerita tentang kehidupan Srintil, seorang ronggeng, dan masyarakat Dukuh Paruk.",
		image: "https://picsum.photos/seed/ronggeng-dukuh-paruk/300/450",
	},
	{
		id: 5,
		title: "Perahu Kertas",
		author: "Dee Lestari",
		year: 2009,
		description: "Kisah perjalanan cinta dan pencarian jati diri antara Kugy dan Keenan.",
		image: "https://picsum.photos/seed/perahu-kertas/300/450",
	},
	{
		id: 6,
		title: "Dilan 1990",
		author: "Pidi Baiq",
		year: 2014,
		description: "Cerita romantis tentang Milea dan Dilan yang bertemu dan menjalani kisah cinta di Bandung.",
		image: "https://picsum.photos/seed/dilan-1990/300/450",
	},
	{
		id: 7,
		title: "Pulang",
		author: "Leila S. Chudori",
		year: 2012,
		description: "Novel yang mengangkat kisah keluarga, persahabatan, dan perjalanan pulang setelah peristiwa politik.",
		image: "https://picsum.photos/seed/pulang/300/450",
	},
	{
		id: 8,
		title: "Cantik Itu Luka",
		author: "Eka Kurniawan",
		year: 2002,
		description: "Kisah keluarga dan sejarah Indonesia yang dikemas melalui perpaduan realisme dan unsur magis.",
		image: "https://picsum.photos/seed/cantik-itu-luka/300/450",
	},
	{
		id: 9,
		title: "Ayat-Ayat Cinta",
		author: "Habiburrahman El Shirazy",
		year: 2004,
		description: "Kisah Fahri selama menjalani kehidupan sebagai mahasiswa Indonesia di Mesir.",
		image: "https://picsum.photos/seed/ayat-ayat-cinta/300/450",
	},
	{
		id: 10,
		title: "Sang Pemimpi",
		author: "Andrea Hirata",
		year: 2006,
		description: "Perjalanan tiga sahabat dalam mengejar pendidikan dan mewujudkan impian mereka.",
		image: "https://picsum.photos/seed/sang-pemimpi/300/450",
	},
	{
		id: 11,
		title: "Hujan",
		author: "Tere Liye",
		year: 2016,
		description: "Kisah tentang persahabatan, kehilangan, cinta, dan harapan di tengah perubahan dunia.",
		image: "https://picsum.photos/seed/hujan/300/450",
	},
	{
		id: 12,
		title: "Aroma Karsa",
		author: "Dee Lestari",
		year: 2018,
		description: "Petualangan tentang pencarian identitas dan kemampuan luar biasa dalam mengenali berbagai aroma.",
		image: "https://picsum.photos/seed/aroma-karsa/300/450",
	},
];

export default books;
